"$schema" = 'https://starship.rs/config-schema.json'

format = """\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
[\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
](fg:color_gray)\
(\
$docker_context\
$conda\
)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_fg1 = '#ebdbb2'
color_gray = '#928374'
color_bg1 = '#3c3836'
color_bg2 = '#504945'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_green_bright = '#b8bb26'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'



[username]
show_always = true
style_root = 'fg:bold color_green_bright bg:color_bg2'
style_user = 'fg:bold color_fg1 bg:color_bg2'
format = '[](color_bg2)[$user]($style)'

[hostname]
ssh_only = false
style = 'fg:color_fg1 bg:color_bg2'
format = '[@$ssh_symbol$hostname ]($style)'


[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1
style = 'bg:color_green_bright fg:color_bg1'
format = """[](fg:color_green_bright bg:color_bg2)\
[$path$read_only]($style)\
[](fg:color_green_bright)"""


[git_branch]
symbol = ''
style = 'fg:color_fg1 bg:color_blue'
format = """[\b[ ](fg:color_green_bright bg:color_blue)\
$symbol$branch(:$remote_branch) ]($style)"""

[git_status]
style = "fg:color_fg1 bg:color_blue"
format = """[$all_status$ahead_behind]($style)\
[](fg:color_blue)"""


[nodejs]
symbol = ""
format = ' $symbol( $version)'

[c]
symbol = " "
format = ' $symbol( $version)'

[rust]
symbol = ""
format = ' $symbol( $version)'

[golang]
symbol = ""
format = ' $symbol( $version)'

[php]
symbol = ""
format = ' $symbol( $version)'

[java]
symbol = " "
format = ' $symbol( $version)'

[kotlin]
symbol = ""
format = ' $symbol( $version)'

[haskell]
symbol = ""
format = ' $symbol( $version)'

[python]
symbol = ""
format = ' $symbol( $version)( [$virtualenv](underline fg:color_gray))'

[docker_context]
symbol = ""
format = ' $symbol( $context)'

[conda]
format = ' $symbol( $environment)'
